name: Create GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'  # Only trigger for version tags

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate release notes (optional)
        id: changelog
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          NOTES=$(awk "/^## ${TAG}/,/^## /" changelog.md | head -n -1 || echo "Release ${TAG}")
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.CHANGELOG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GREET_AUTO_RELEASE_TOKEN }}
